#!/bin/sh

# TODO:
# * support versioned symbols
# * compile with -ffreestanding to avoid autogenerated memset and crap

set -e

cd $(dirname $0)

mkdir -p bin
rm -f bin/*

scripts/gendefs.py bin/

CPPFLAGS='-Iinclude -Ibin -D_GNU_SOURCE'

CFLAGS='-g -O2'
CFLAGS="$CFLAGS -Wall -Wextra -Werror"
CFLAGS="$CFLAGS -fvisibility=hidden -fPIC -shared"
#CFLAGS="$CFLAGS -g -O0 -save-temps"

LDFLAGS='-Wl,--no-as-needed -ldl -lm -lpthread'

gcc -o bin/libsigtester.so src/*.c $CPPFLAGS $CFLAGS $LDFLAGS

# Quick check
SIGTESTER_VERBOSE=1 LD_PRELOAD=bin/libsigtester.so bash -c 'whoami; whoami'

