#!/bin/sh

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.

# Script to find candidate executables.

set -e

is_executable() {
  file "$1" | grep -qF ELF
}

does_use_signals() {
  readelf --dyn-syms -W "$1" | grep -q 'UND.*\<\(signal\|sigaction\)\>'
}

count_signals() {
  objdump -d "$1" | grep -c '\<\(signal\|sigaction\)\>'
}

for f in $(find /bin /usr/bin -type f -a -executable); do
  if is_executable $f && does_use_signals $f; then
    num_calls=$(count_signals $f)
    echo "$f: $num_calls"
  fi
done | sort -t ' ' -rnk2

