#!/bin/sh

# Sigcheck examples.

cd $(dirname $0)/..

SIGCHECK=bin/sigcheck

runtest() {
  echo "$@ (atexit)"
  SIGCHECK_FORK_TESTS=atexit SIGCHECK_OUTPUT_FILENO=3 \
    timeout 5 $SIGCHECK "$@" 3>&1 >/dev/null 2>&1

  echo "$@ (onset)"
  SIGCHECK_FORK_TESTS=onset SIGCHECK_OUTPUT_FILENO=3 \
    timeout 5 $SIGCHECK "$@" 3>&1 >/dev/null 2>&1
}

runtest ls

runtest bash -c 'whoami; whoami'

runtest dash -c 'whoami; whoami'

touch 1
runtest tar czf 1.tgz 1
runtest tar cjf 1.tar.bz2 1
runtest tar cJf 1.tar.xz 1
rm -f 1.tgz 1.tar.bz2 1.tar.xz 1

runtest /usr/bin/man bash

runtest info bash

runtest strace ls

runtest git branch

runtest ssh-keygen -t rsa -f tmp.dat -N ''
rm -f tmp.dat*

touch 1
runtest zip 1.zip 1
rm -f 1 1.zip

runtest wget 'http://google.ru'
rm -f index.html

echo 'Hello world' > 1
runtest aspell -c 1
rm -f 1

echo 'Hello world' > 1
echo 'Hello worldd' > 2
runtest diff 1 2
rm -f 1 2

echo -e '1\n2' > 1
runtest sort 1
rm -f 1

runtest make -d
rm -f 1

runtest calendar -A 10
rm -f 1

runtest gpg --list-public-keys
rm -f 1

runtest gdb -ex run -ex quit ls

