#!/bin/sh

# Sigcheck examples.

cd $(dirname $0)/..

LIBSIGCHECK=$PWD/bin/libsigcheck.so

export SIGCHECK_FORK_TESTS=1

echo '== ls =='
LD_PRELOAD=$PWD/bin/libsigcheck.so ls

echo '== bash =='
LD_PRELOAD=$PWD/bin/libsigcheck.so bash -c 'whoami; whoami'

echo '== dash =='
LD_PRELOAD=$PWD/bin/libsigcheck.so dash -c 'whoami; whoami'

echo '== tar =='
touch 1
LD_PRELOAD=$PWD/bin/libsigcheck.so tar -czf 1.tgz 1
rm -f 1.tgz 1

echo '== man =='
LD_PRELOAD=$PWD/bin/libsigcheck.so /usr/bin/man bash > /dev/null

echo '== info =='
LD_PRELOAD=$PWD/bin/libsigcheck.so info bash > /dev/null

echo '== strace =='
LD_PRELOAD=$PWD/bin/libsigcheck.so strace ls > /dev/null 2>&1

echo '== git =='
LD_PRELOAD=$PWD/bin/libsigcheck.so git branch > /dev/null

echo '== ssh-keygen =='
LD_PRELOAD=$PWD/bin/libsigcheck.so ssh-keygen -t rsa -f tmp.dat -N '' > /dev/null
rm -f tmp.dat*

echo '== zip =='
touch 1
LD_PRELOAD=$PWD/bin/libsigcheck.so zip 1.zip 1 > /dev/null
rm -f 1 1.zip

echo '== wget =='
LD_PRELOAD=$PWD/bin/libsigcheck.so wget 'http://google.ru' > /dev/null
rm -f index.html

echo '== aspell =='
echo 'Hello world' > 1
LD_PRELOAD=$PWD/bin/libsigcheck.so aspell -c 1 > /dev/null
rm -f 1

