#!/bin/sh

# Copyright 2015-2016 Yury Gribov
# 
# Use of this source code is governed by MIT license that can be
# found in the LICENSE.txt file.
LD_PRELOAD=$(dirname $0)/libsigcheck.so${LD_PRELOAD:+:$LD_PRELOAD} "$@"
